### ISSUE TITLE
Add phylogenetic beta diversity to available metrics

### ISSUE THREAD

**Issue by cjgrady** [biotaphy/analyses#16]
**Is your feature request related to a problem? Please describe.**
@blackrim suggested that it would be useful for users to be able to compute phylogenetic beta diversity, similar to the R method "phylo.beta.pair".

**Describe the solution you'd like**
Methods for calculating the various phylogenetic beta diversity metrics provided by "phylo.beta.pair".

**Comment by cjgrady** [comment]
I will add the basics for where the code should be in the repository and maybe even the function calls themselves before handing it over to Hannah and Hector.  I will likely have questions.

**Comment by cjgrady** [comment]
I believe that the arguments for these functions are a PAM and a tree and potentially options about which method(s) to use, is that correct?  Ideally, this metric could be calculated one site at a time so we can take advantage of some parallelism from Numpy as well as the basic structure I have for site statistics that I will be adding to this repository soon.

**Comment by hmarx** [comment]
Correct, should just require a PAM and tree as input, plus a methods option. Should also be able to calculate in parallel. Actually just found pretty much what we want to do implemented for the microbiome (https://github.com/biocore/scikit-bio). Still think we want to modify to partition turnover and nestedness/PD components.

**Comment by cjgrady** [comment]
Adding scikit-bio as a dependency would cause a few problems.  The biggest being that it would break Python 2 compatibility (which is currently required by the deployment architecture we are using at Lifemapper).  If at all possible, I would like to allow Python 2.7.  Can we determine if that implementation is using scipy or numpy under the hood and just use the same function?

**Comment by hmarx** [comment]
Got it, will do!

**Comment by cjgrady** [comment]
@hmarx @foxgiteeb, I created a branch called phylo-beta-diversity with some code stubs for you.

You should modify the methods in `analyses/phylo_beta_diversity/phylo_beta_diversity.py`.  

I set the tests up so that the resulting matrices should be site by site (instead of site by site -1) and they should be symmetric.  I ran the example on https://rdrr.io/rforge/betapart/man/phylo.beta.pair.html to generate test output values and I filled them in test matrices in 
`tests/test_phylo_beta_diversity/test_phylo_beta_diversity.py`. 

It is very possible that there are some typos or there will be some rounding errors.  Let me know if you run into anything or if anything is confusing.  The computations use "lm_objects" for trees and matrices.  These objects are used by Lifemapper and by using them, we can deploy this code on our clusters.

This is a good test case for us to find out where any code documentation is lacking, so I encourage you to ask questions!

You can use pytest to run all of the tests on the repository and show you any errors or code style that it doesn't like.  It is fairly pedantic but common.  Use something like:
 `pytest tests/ --pep8 analyses -v --cov analyses --cov-report term-missing` 
from the root of the repository to run all of the tests.

**Comment by hmarx** [comment]
We are not able to locate the test matrices for some reason. Can't find the directory: tests/test_phylo_beta_diversity/test_phylo_beta_diversity.py.

**Comment by cjgrady** [comment]
Make sure your branch is up to date.  You may have cloned before I added the test code.

```
$ git checkout phylo-beta-diversity
$ git pull
```

**Comment by hmarx** [comment]
@cjgrady: We just pushed updated to phylo-beta-diversity. We still need to finish the non-phylo parts for this to pass the tests, but wanted to share what we have so far.

**Comment by cjgrady** [comment]
Great job so far!  Keep me updated with your progress.

The PEP8 checks are going to force some code style changes.  I can help with those if you want.

**Comment by hmarx** [comment]
Hector and I just ran the pytest checks on our updated phylo-betat-diversity code, and they all passed. We did find a few typos in test_phylo_beta_diversity.py, and made notes where we corrected the values to those from R output. We are fine with making whatever code style changes are necessary with the PEP8 checks, if you could give us a bit more information about all that!

**Comment by cjgrady** [comment]
That's fantastic!  Great work!  I just checked the travis build and it looks like the tests are passing, except for PEP8.

Most of the PEP8 style changes look to be related to spacing.  I think R adds more padding around things than python.  If you run (from the repo root):

```
$ pytest-3 tests/ --pep8 analyses/ -v --cov analyses --cov-report term-missing
```

It should list all of the things PEP8 doesn't like.  It is generally pretty specific and it looks like mostly it doesn't like extra spaces around variables.  You may find it useful to start at the bottom of a file and work up towards the top.  Starting from the top and moving down often changes line numbers where the issues are found.  Let me know if you have any questions!

**Comment by hmarx** [comment]
I just pushed the latest update with the PEP8 style changes Hector implemented. We will try it out on an larger dataset next week!

**Comment by cjgrady** [comment]
Looks pretty good!  There were a few syntax errors since python won't let you end a statement with an equals sign but I went ahead and fixed them and pushed a few updates.  

I am going to merge your changes into the master branch so you get some credit on the repo.  I will close this bug as well since the computations are now available but we should still test them a bit more and add an easy method for accessing them.

Great job on your contributions!
