### ISSUE TITLE
No projections were returned. output message 

### ISSUE THREAD

**Issue by hmarx** [biotaphy/analyses#68]
I was just testing the web client and keep getting a "No projections were returned." output message. Tried multiple models and get the same thing.

**Comment by cjgrady** [comment]
Which projects were you looking at?  A lot of the recent anonymous data is garbage that I need to delete.  But if it is something else I will dig deeper

**Comment by hmarx** [comment]
I made my own account and was using my own test list of species, and then tried the max ent, biofilm, and climate space models with default parameters and the first SDM model (AR5, Community Climate System Model, 4.0, RCP4.5, 2041-2060, 10min). I only get this output error message. Stephen was also trying with a different list and had the same error. Here is the list I was using:

Arenaria globiflora
Bolanthus cherlerioides
Colobanthus subulatus
Dianthus nitidus
Eremogone bryophylla
Gypsophila aretioides
Mcneillia saxifraga
Moehringia trinervia
Moenchia erecta
Petrorhagia alpina
Pteranthus dichotomus
Sabulina juniperina
Silene andicola
Silene caryophylloides
Atraphaxis frutescens
Oxyria digyna
Pteropyrum olivieri
Rheum moorcroftianum
Claytonia perfoliata
Pollichia campestris
Spergularia bocconei

**Comment by cjgrady** [comment]
This seems to be an issue with unicode in the author portion of the scientific name.  I'll let you know when I figure it out for sure and when we have a fix in place.

**Comment by cjgrady** [comment]
I had to clear some data to figure it out, but I believe that it is fixed.  Can you submit a new project to see if it works for you?

**Comment by hmarx** [comment]
I am now getting the output from the SDM model, but nothing for PAM stats. And I get this error when trying to download the results package:

406 Not Acceptable
Failed: Cannot load file: /share/lm/data/archive/hmarx/anc_pam_2413.lmm, [Errno 2] No such file or directory: '/share/lm/data/archive/hmarx/anc_pam_2413.lmm'

**Comment by cjgrady** [comment]
I just pushed out a fix for this.  See if you can download your package now.

**Comment by hmarx** [comment]
It's working now! Thanks CJ!

**Comment by cjgrady** [comment]
Great!  Let me know if you see anything else.
