### ISSUE TITLE
Delete old projects?

### ISSUE THREAD

**Issue by hmarx** [biotaphy/analyses#69]
Currently it doesn't seem possible to delete old projects in the web client. Is there a way to do this that I am missing?

**Comment by Amit55555kk** [comment]
> Currently it doesn't seem possible to delete old projects in the web client. Is there a way to do this that I am missing?

**Comment by cjgrady** [comment]
This is a limitation in the UI.  I have opened your issue in the UI repo at: https://github.com/lifemapper/viz_client/issues/20
